### ISSUE TITLE
Please provide release tags on this Git repository

### ISSUE THREAD

**Issue by medienverbinder** [threema-ch/threema-msgapi-sdk-php#1]
Hi,

thanks for the great PHP SDK. To manage it with Composer I think it would be good when git tags could be supported. Can you provide a tag for that latest release 1.0.4?

Best regards

medienverbinder

**Comment by threema-ch** [comment]
done

**Comment by medienverbinder** [comment]
Thank You!

**Comment by rugk** [comment]
@threema-ch Can you please also provide a git tag/release for version 1.1.0?

**Comment by threema-ch** [comment]
done!

**Comment by rugk** [comment]
So I think you can close this now. :smiley:

**Comment by rugk** [comment]
Don't want to close this issue? :wink:
