### ISSUE TITLE
Short private & public key? SHA-265 hash?

### ISSUE THREAD

**Issue by rugk** [threema-ch/threema-msgapi-sdk-php#11]
While creating a test key pair with Sodium 1.0.3 I've got only very small private and public key files.
The public key file is this:

    public:a27450df86144478ff4cc0e59e8bb307533e19116cc108d87f424d231417ad43

The private key file is formed the same.

I highly doubt this is a (complete) key pair.
In my view this rather looks like a SHA-256 hash of a cert, but where is the actual cert? Does libsodium save it somewhere else?

**Comment by threema-ch** [comment]
This is indeed the actual public key. ECC keys over Curve25519 (as used by libsodium and Threema) are 256 bits long. There are no certificates, just raw keys.
