### ISSUE TITLE
Provide possibility to force TLS version

### ISSUE THREAD

**Issue by rugk** [threema-ch/threema-msgapi-sdk-php#12]
It would be good if you could specify the TLS version to use when connecting manually.
I mean the MsgAPI server only supports TLS 1.0 above, but as a server operator you certainly know what you support too (which should be TLS 1.2).
And I mean TLS 1.0 and also TLS_FALLBACK_SCSV are consider secure (enough) it's always good to not rely on it and choose the best TLS version. Just to stay away from the next SSL/TLS vulnerability. :wink: 

To do this you just have to add [an option] (https://secure.php.net/manual/en/function.curl-setopt.php) named ```CURLOPT_SSLVERSION```.

And to be really strict you can also add ```CURLOPT_SSL_CIPHER_LIST``` where you can effectively only allow one cipher. (And again: as you control the server and know what ciphers the MsgAPI server supports you can limit this very nice)

**Comment by threema-ch** [comment]
Thank you for your feedback. The SDK is intended to be as compatible with the various PHP and system/OpenSSL versions as possible without requiring detailled TLS configuration. Please free to add this feature to your own fork, or submit a pull request.
