### ISSUE TITLE
The entropy issue

### ISSUE THREAD

**Issue by rugk** [threema-ch/threema-msgapi-sdk-php#13]
Productive servers are at risk to run out of enough entropy. See https://www.blackhat.com/us-15/briefings.html#understanding-and-managing-entropy-usage and https://www.calomel.org/entropy_random_number_generators.html.
Unfortunately this entropy is and I assume it's both needed for the E2E encryption and the TLS connection.
Don't forget the time when you create the cert first.

At least for the last thing you could try to add additional entropy by entering some stuff into the console before you create the cert or even create the cert on a productive device and move the cert to the server.
The problem is for all encryption steps later you also need entropy AFAIK.

CURL BTW [provides] (https://secure.php.net/manual/en/function.curl-setopt.php) ```CURLOPT_RANDOM_FILE``` which can be used to add entropy - it's just the question which what it can be filled.

**Comment by threema-ch** [comment]
Managing entropy is not the job of this SDK. The operating system should ensure that the system's RNG provides an adequate supply of high quality random data. If in doubt, the user can always add additional entropy, e.g. by writing to /dev/random on UNIX systems, before executing sensitive operations like generating key pairs. In practice, insufficient entropy is mostly a problem of freshly cloned virtual machines and embedded systems.

Once a key pair has been generated, the actual Threema E2E message encryption does not need high quality entropy, as randomness is only used for per-message nonce generation.
