### ISSUE TITLE
Does not work with libsodium-php 0.2.0 or higher

### ISSUE THREAD

**Issue by rugk** [threema-ch/threema-msgapi-sdk-php#5]
The issue is that the Sodium class  [was removed] (https://github.com/jedisct1/libsodium-php/pull/30) with version 0.2.0 and added as a namespace in libsodioum-php. 

And if you want to use it with 0.2.0 or higher it will return: ```ERROR: no supported crypt-tool```

**Comment by threema-ch** [comment]
issue will be fixed in next version

**Comment by rugk** [comment]
Thanks. Can you probably say when this will be released to GitHub?
And will the new version still support older versions of libsodium (< 0.2.0)?

From: FWD_VlvldqUA@opayq.com
To: c917250b@opayq.com
Date: Sun, 16 Aug 2015 04:13:03 -0700
CC: c917250b@opayq.com
Subject: Re: [threema-msgapi-sdk-php] Does not work with libsodium-php 0.2.0 or higher (#5)



  
    Preview: issue will be fixed in next version --- Reply to this email d

    This email is forwarded from a MASKED EMAIL you created using DoNotTrackMe.

    IF THIS IS SPAM, CLICK HERE TO BLOCK.

    

    Want to shop safely and privately online? Get DoNotTrackMe Premium.
  




issue will be fixed in next version

**Comment by threema-ch** [comment]
The new version will be released this month, and yes, the old version of libsodium will be supported.

**Comment by rugk** [comment]
:+1:

**Comment by rugk** [comment]
So I think this is fixed with v 1.1.0 now.
