### ISSUE TITLE
[Insights] Files should not be executable & more

### ISSUE THREAD

**Issue by rugk** [threema-ch/threema-msgapi-sdk-php#7]
I've just ran a scan with Sensio Labs Insights on my fork of this repo and I got the following message:
> Your project contains files with permissive permissions. In order to avoid opening a security breach, you should restrict execution rights on following files:

>    source/Salt/Curve25519/Curve25519.php
    source/Salt/FieldElement.php
    source/Salt/Poly1305/Poly1305.php
    source/Salt/Salsa20/Salsa20.php
    source/Salt/Salt.php
    source/Salt/SaltException.php
    source/Salt/autoload.php

Here is an link: https://insight.sensiolabs.com/projects/0d2aa31f-7a59-44a1-b8cf-62a0a264eab5/analyses/3?status=violations#324096784

Personally I don't know a repo can have such permissions at all, because I thought it would only store files, but @SensioLabs reports this.

There are also a few other minor errors. You can also have a look at them too.
I think at least [this] (https://insight.sensiolabs.com/projects/0d2aa31f-7a59-44a1-b8cf-62a0a264eab5/analyses/3?status=violations#324096788) would also be nice to change.

**Comment by threema-ch** [comment]
Thank you for your input. The next version (1.2.0) of the php-sdk will be released soon and some of these bugs will be fixed in this version.

**Comment by rugk** [comment]
Okay, great.

**Comment by rugk** [comment]
BTW you can also configure [Insides] (https://insight.sensiolabs.com/) on this repo, so I don't have to scan my fork and copy and paste the issues.
With a few limitations it's free and it rescans the code after each commit.

**Comment by rugk** [comment]
FYI here is another code analyser: https://codeclimate.com/github/threema-ch/threema-msgapi-sdk-php
[![Code Climate](https://codeclimate.com/github/threema-ch/threema-msgapi-sdk-php/badges/gpa.svg)](https://codeclimate.com/github/threema-ch/threema-msgapi-sdk-php)

Funny is that he often complains about the complexity of the code - but, well... Cryptography is complex :wink:

**Comment by rugk** [comment]
FYI here is another code analyser: https://codeclimate.com/github/threema-ch/threema-msgapi-sdk-php
[![Code Climate](https://codeclimate.com/github/threema-ch/threema-msgapi-sdk-php/badges/gpa.svg)](https://codeclimate.com/github/threema-ch/threema-msgapi-sdk-php)

Funny is that he often complains about the complexity of the code - but, well... Cryptography is complex :wink:

**Comment by threema-ch** [comment]
The most of the issues are in the pure PHP-Salt implementation. For more informations: https://github.com/devi/Salt

**Comment by rugk** [comment]
Yes I already saw this. But most is not everything... :wink: 
So you might just fix your own issues...
(v 1.2 is not released yet so you can change them until this release)

Maybe you should also consider using a git submodule (see #23). AFAIK the code analysis should only scan your own repo in this case.

**Comment by rugk** [comment]
BTW I've created an issue at the Salt repo: https://github.com/devi/Salt/issues/4

This are the current results of the PHP SDK here:
[![Code Climate](https://codeclimate.com/github/threema-ch/threema-msgapi-sdk-php/badges/gpa.svg)](https://codeclimate.com/github/threema-ch/threema-msgapi-sdk-php)

[![SensioLabsInsight](https://insight.sensiolabs.com/projects/bea330a9-9549-4bd7-9cac-cbdb0a292726/big.png)](https://insight.sensiolabs.com/projects/bea330a9-9549-4bd7-9cac-cbdb0a292726)

At the Sensiolabs test i also excluded `source/Salt` now, so you really only see your own issues.
At Codeclimate.com you can also adjust the settings and exclude some files, however you have to place the config file in your repo to do this.
