### ISSUE TITLE
Public key store file publicy accessible

### ISSUE THREAD

**Issue by rugk** [threema-ch/threema-msgapi-sdk-php#8]
**Edit: All website owner who use this SDK and read this I would strongly recommend to block web access to the ```keystore.txt``` with an .htaccess (Apache) or something similar, depending on your webserver.**

----

[Here] (https://github.com/threema-ch/threema-msgapi-sdk-php/blob/master/samples/testSendE2EFile.php#L15) you recommend a txt file for storing the public key. I just wonder why you use a txt file for this. I mean does this key have to be accessible for the Threema MSGAPI server?
Or why is this necessary?

**Comment by rugk** [comment]
Or do I get something wrong...
So what public key(s) are stored there?
The own one or the ones of the receivers?
**Edit:** Just saw by looking into the  code that it stores the public keys of receivers.

So I would say the recommendation to use a txt file is very bad. I mean you hope webmaster configure their server in a way that the file(s) is/are not publicly accessible, but you can never be sure.
So a kind of php file (which would have to be formatted correctly of course and put all this things into a variable for example) would be better, because if the file is accessible from outside an attacker could possibly get out what IDs the server sends messages to.

**Comment by threema-ch** [comment]
Good point, but you have the same Problem with your private key file. 

If you don't want a public key store, you can instantiate the Connection class without a PublicKeyStore implementation (second argument).

Feel free to implement a PHP-PublicKeyStore or another (Database or Crypted File) implementation.

**Comment by rugk** [comment]
Yes, but with the private key you explicitly have to specify (the file path), so web admins hopefully know what they are doing and protect it. The keystore.txt is created automatically, so in the worst case they won't even notice it is created and used. (or if they do they are not aware that this can be a privacy issue)
Maybe a notice in the Readme about the fact could already be helpful.

**Comment by threema-ch** [comment]
The auto-creation of the keystore happens only on the cli tool.
If you use the sdk in your php-application, you have to specity explicity the file path to your keystore.
We will make a notice in the Readme.
Thank you

**Comment by rugk** [comment]
Well... okay. It's just that nearly everyone uses the CLI tool for creating the keys. At least I assume this, because no one first creates a script for doing an action which is only done one.

So you can close this issue if the Readme notice is added. At the current stage that's the best thing to do.
Maybe I'll have a look into adding another key store provider at some point.
