### ISSUE TITLE
Some unmentioned and unexplaned changes in v 1.1.0

### ISSUE THREAD

**Issue by rugk** [threema-ch/threema-msgapi-sdk-php#9]
[In your commits of v1.1.0] (https://github.com/threema-ch/threema-msgapi-sdk-php/commits/v1.1.0) I saw that you mentioned these things:
* support capability check of a identity
* public key store implementation (related: https://github.com/threema-ch/threema-msgapi-sdk-php/issues/8)
* enable curl safe upload

What exactly do these changes exactly mean? 
I've had a quick look over your source code, but you committed many changes at once. So can you please provide a short explanation?

**Comment by rugk** [comment]
And BTW the change of 'enable curl safe upload' is not included in *threema-msgapi-tool.php* AFAIK. (because you haven't updated it after the commit where you added the command).

**Comment by threema-ch** [comment]
Thank you, the threema_msgapi.phar is now up to date.

The changes of the v1.1.0 are the implementation of the new api methods blob-upload, blob-download and id-capability (see https://gateway.threema.ch/en/developer/api), a new console client environment and the new ThreemaMessage Types Image and File.

**Comment by rugk** [comment]
> id-capability 
Ah okay, so with 'support capability check of a identity' you mean the part 'Check file reception capability of an ID'. Okay.
And while looking in #8 I also understand what the public key store is.
